=== mirage2032/resume/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "name": {
      "type": "object",
      "properties": {
        "first": {
          "type": "string"
        },
        "middle": {
          "type": "string"
        },
        "last": {
          "type": "string"
        }
      },
      "required": [
        "first",
        "middle",
        "last"
      ]
    },
    "photo": {
      "type": "string",
      "format": "uri"
    },
    "description": {
      "type": "string"
    },
    "contact": {
      "type": "object",
      "properties": {
        "phone": {
          "type": "string"
        },
        "email": {
          "type": "string",
          "format": "email"
        },
        "location": {
          "type": "object",
          "properties": {
            "city": {
              "type": "string"
            },
            "country": {
              "type": "string"
            }
          },
          "required": [
            "city",
            "country"
          ]
        },
        "website": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "name": {
                "type": "string"
              },
              "uri": {
                "type": "string",
                "format": "uri"
              }
            },
            "required": [
              "name",
              "uri"
            ]
          }
        }
      },
      "required": [
        "phone",
        "email",
        "location",
        "website"
      ]
    },
    "education": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "location": {
            "type": "object",
            "properties": {
              "city": {
                "type": "string"
              },
              "country": {
                "type": "string"
              }
            },
            "required": [
              "city",
              "country"
            ]
          },
          "degree": {
            "type": "string"
          },
          "major": {
            "type": "string"
          },
          "interval": {
            "type": "object",
            "properties": {
              "start": {
                "type": "string",
                "format": "date"
              },
              "end": {
                "type": [
                  "string",
                  "null"
                ],
                "format": "date"
              }
            },
            "required": [
              "start",
              "end"
            ]
          }
        },
        "required": [
          "name",
          "location",
          "degree",
          "major",
          "interval"
        ]
      }
    },
    "work": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "position": {
            "type": "string"
          },
          "interval": {
            "type": "object",
            "properties": {
              "start": {
                "type": "string",
                "format": "date"
              },
              "end": {
                "type": [
                  "string",
                  "null"
                ],
                "format": "date"
              }
            },
            "required": [
              "start",
              "end"
            ]
          },
          "lines": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "skills": {
            "type": "array",
            "items": {
              "type": "string"
            }
          }
        },
        "required": [
          "name",
          "position",
          "interval",
          "lines",
          "skills"
        ]
      }
    },
    "languages": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "level": {
            "type": "string"
          }
        },
        "required": [
          "name",
          "level"
        ]
      }
    },
    "skills": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "technologies": {
      "type": "object",
      "properties": {
        "languages": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "others": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      },
      "required": [
        "languages",
        "others"
      ]
    },
    "projects": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "description": {
            "type": "string"
          },
          "uri": {
            "type": "string",
            "format": "uri"
          }
        }
      }
    }
  },
  "required": [
    "name",
    "photo",
    "description",
    "contact",
    "education",
    "work",
    "languages",
    "skills",
    "technologies",
    "projects"
  ]
}

=== mirage2032/resume/resume.json
{
    "name": {
        "first": "Alexandru",
        "middle": "Ionut",
        "last": "Popescu"
    },
    "photo": "https://img.freepik.com/premium-vector/happy-banana-cartoon-mascot-illustration_360091-201.jpg",
    "description": "Passionate software developer with hands-on experience since the first year of Computer Science studies. Currently in my final year, I excel at finding innovative solutions to complex problems and am eager to embrace new opportunities in the tech industry.",
    "contact": {
        "phone": "+40-742-595-723",
        "email": "pialex2032@gmail.com",
        "location": {
            "city": "Pitesti",
            "country": "Romania"
        },
        "website": [
            {
                "name": "github",
                "uri": "https://github.com/mirage2032"
            },
            {
                "name": "fiverr",
                "uri": "https://fiverr.com/mirage2032"
            },
            {
                "name": "linkedin",
                "uri": "https://linkedin.com/in/pialex"
            }
        ]
    },
    "education": [
        {
            "name": "Universitatea Politehnica Bucuresti",
            "location": {
                "city": "Pitesti",
                "country": "Romania"
            },
            "degree": "Bachelors",
            "major": "Computer Science",
            "interval": {
                "start": "2021-09-30",
                "end": "2025-07-03"
            }
        }
    ],
    "work": [
        {
            "name": "ASML",
            "position": "Software Engineer",
            "interval": {
                "start": "2022-05-23",
                "end": null
            },
            "lines": [
                "Backend Python development on Linux RedHat systems",
                "Collaborating with Product Owners and Architects about the direction and architecture of the product",
                "Play a role in designing the architecture of new products.",
                "Build and maintain a CI/CD pipeline for faster and reliable delivery",
                "Develop Docker containers to improve development efficiency",
                "Design and develop software based on specifications",
                "Create, develop and execute unit tests and integration tests",
                "Write and maintain product documentation"
            ],
            "skills": [
                "Docker",
                "Python",
                "Linux (RedHat)",
                "CI/CD",
                "AGILE",
                "Software Architecture",
                "Jira",
                "C++",
                "Shell",
                "Databases",
                "Git"
            ]
        },
        {
            "name": "Fiverr (Freelance)",
            "position": "Software Developer",
            "interval": {
                "start": "2019-04-12",
                "end": null
            },
            "lines": [
                "Build and maintain web scraping/crawling bots",
                "Build task automation software based on customer request",
                "Collaboratee with the customer to meet expectations"
            ],
            "skills": [
                "Python",
                "API Reverse Engineering",
                "C++",
                "Web Scraping",
                "MySQL",
                "PostgreSQL",
                "MongoDB",
                "Automation"
            ]
        },
        {
            "name": "CGS (Computer Generated Solutions)",
            "position": "Technical Support Specialist",
            "interval": {
                "start": "2022-02-13",
                "end": "2022-05-20"
            },
            "lines": [
                "Assist technical business customers in troubleshooting",
                "Keep in touch with key customers to investigate possible issues with their product and service quality"
            ],
            "skills": [
                "Soft Skills",
                "Troubleshooting"
            ]
        },
        {
            "name": "Valoris",
            "position": "Customer Support Agent",
            "interval": {
                "start": "2020-11-13",
                "end": "2022-02-10"
            },
            "lines": [
                "Remotely assist customers with technical and commercial issues.",
                "Maintained a comprehensive understanding of company products, services, and policies to offer accurate information and support.",
                "Identified and escalated complex issues to the appropriate departments, ensuring timely and efficient problem resolution."
            ],
            "skills": [
                "Soft Skills",
                "Troubleshooting"
            ]
        }
    ],
    "languages": [
        {
            "name": "romanian",
            "level": "native"
        },
        {
            "name": "english",
            "level": "fluent"
        }
    ],
    "skills": [
        "Critical Thinking",
        "AGILE",
        "Teamwork",
        "Software Design",
        "Containers",
        "Communication",
        "Adaptive",
        "Time Management"
    ],
    "technologies": {
        "languages": [
            "Python",
            "Rust",
            "C/C++",
            "Go",
            "Javascript/Typescript",
            "Shell",
            "MySQL/PostgreSQL"
        ],
        "others": [
            "Debugging",
            "Kernel Development",
            "Linux",
            "Web Crawling",
            "Api Development",
            "Api Reverse Engineering",
            "Binary Reverse Engineering",
            "Database ORM",
            "CI/CD Pipelines",
            "Unit Testing",
            "Docker",
            "Github Actions",
            "Version Control (Git)",
            "Test Driven Development",
            "Remote Development",
            "Networking"
        ]
    },
    "projects": [
        {
            "name": "Zilog Z80 emulator",
            "description": "A Zilog Z80 debugger/assembler/dissasembler library written in Rust",
            "uri": "https://github.com/mirage2032/rs_emu_lib"
        },
        {
            "name": "OpenGL Game engine in Rust",
            "description": "A game engine using OpenGL written in Rust",
            "uri": "https://github.com/mirage2032/rustgraphics"
        },
        {
            "name": "Conway's Game of Life on GPU in C++",
            "description": "A simulation of Conway's Game of Life cellular automata using the interoperability between OpenCL and OpenGL",
            "uri": "https://github.com/mirage2032/CGOL_CLGL_Interop"
        },
        {
            "name": "Chip8 Emulator in C++",
            "description": "A Chip8 Emulator written in C++",
            "uri": "https://github.com/mirage2032/Chip8Emu"
        },
        {
            "name": "Newtonian Physics simulation",
            "description": "A simulator for gravitational pull between objects in space accurate to real life.",
            "uri": "https://github.com/mirage2032/rust-particle-simulator"
        }
    ]
}
